#!/bin/bash
#
#    99-footer - write the admin's footer to the MOTD
#    Copyright (C) 2009-2010 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


# motd.tail is reserved for the admin to append static
# trailing information to a dynamically generated
# /etc/motd.
#
# To add dynamic information, add a numbered
# script to /etc/update-motd.d/

# [ -f /etc/motd.tail ] && cat /etc/motd.tail || true


serial_number="Serial: `cat /etc/opt/ninja/serial.conf`"
node_version="Version: `grep version /opt/ninja/package.json | cut -d: -f 2 | sed 's/[ ",]//g'`"

echo "
           MMMMMMMMMMMMMMMMMM 
         MMMMMMMMMMMMMMMMMMMMMM
         MM                  MM          $node_version
        MM    MMMM     MMMM    MM        $serial_number
        MM    MMMM     MMMM    MM
         MM                   MM 
         MMMMMMMMMMMMMMMMMMMMMM 
         MMMMMMMMMMMMMMMMMMMMMM
             MMMMMMMMMMMMMM        
             MMMMMMMMMMMMMM          
         MMMMMMMMMMMMMMMMMMMMMMM        
         MMMMMMMMMMMMMMMMMMMMMMM        
         MMMMMMMMMMMMMMMMMMMMMMM         
              MMMMMMMMMMMM            
              MMMMMMMMMMMM            
              MMMMMMMMMMMM             
             MMMMMMMMMMMMMM            
             MMMMM    MMMMM            
            MMMMM      MMMMM            
            MMMMM      MMMMM
"








